-- MySQL Script generated by MySQL Workbench
-- 07/18/15 18:10:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogger` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blogger` ;

-- -----------------------------------------------------
-- Table `blogger`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogger`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `login_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogger`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogger`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descricao_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogger`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogger`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_post` DATETIME NULL,
  `titulo_post` VARCHAR(45) NOT NULL,
  `bloqueado_post` BINARY(1) NOT NULL DEFAULT 1 COMMENT '1 -> Post Ativo\n0 -> Post Bloqueado',
  `text_post` TEXT NULL,
  `criado_post` DATETIME NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_post_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_post_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `blogger`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `blogger`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogger`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogger`.`imagem` (
  `id_imagem` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `descricao_imagem` VARCHAR(45) NULL,
  `destaque_imagem` BINARY NULL DEFAULT 0 COMMENT '0 -> Não é destaque\n1 -> É destaque',
  `nome_imagem` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_imagem`),
  INDEX `fk_imagem_post_idx` (`id_post` ASC),
  CONSTRAINT `fk_imagem_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `blogger`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
